name: Static analysis

on:
  push:
    branches: [main]
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
defaults:
  run:
    shell: bash

jobs:
  phpstan:
    name: "PHPStan"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          extensions: "dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, gd"
          ini-values: "memory_limit=-1"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-composer-packages
        with:
          path: "**/"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.php-version }}

      - name: "Install dependencies"
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: "composer install --no-progress --prefer-dist"

      - name: "PHPStan"
        run: "php vendor/bin/phpstan analyze"
